version: '3.9'

services:
  app:
    image: 'messenger-services:latest'
    build:
      context: ./messenger-services
    container_name: app
    ports:
      - "8081:8080"
    depends_on:
      - appdb
    networks:
      - my-private-network

  appdb:
    image: 'postgres:13.1-alpine'
    container_name: appdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=madMAL123
    ports:
      - "54321:5432"
    networks:
      - my-private-network

networks:
  my-private-network:
    driver: bridge