version: '3'

services:
  messengerproxy:
    image: 'addepallimadhu/messenger-proxy:latest'
    build:
      context: ./messenger-proxy
    ports:
      - "3003:3003"
    depends_on:
      - messengerapp
      - messengerweb
      - messengerappdb
    networks:
      - my-private-network

  messengerweb:
    image: 'addepallimadhu/messenger-ui:latest'
    build:
      context: ./messenger-ui
    container_name: messengerweb
    ports:
      - "80:80"
    depends_on:
      - messengerapp
      - messengerappdb
    networks:
      - my-private-network
    links:
      - "messengerapp:messengerapp"

  messengerapp:
    image: 'addepallimadhu/messenger-services:latest'
    build:
      context: ./messenger-services
    container_name: messengerapp
    environment:
      - spring_profiles_active=docker
    ports:
      - "8080:8080"
    depends_on:
      - messengerappdb
    networks:
      - my-private-network

  messengerappdb:
    image: 'addepallimadhu/messenger-db:latest'
    build:
      context: ./messenger-services
      dockerfile: DockerfilePostGresDB
    container_name: messengerappdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=*****
    ports:
      - "5432:5432"
    networks:
      - my-private-network

networks:
  my-private-network:
    driver: bridge
