version: '3.9'

services:
  app:
    image: 'messenger-services:latest'
    build:
      context: ./messenger-services
    container_name: messengerapp
    environment:
      - spring_profiles_active=docker
    ports:
      - "8081:8080"
    depends_on:
      - messengerappdb
    networks:
      - my-private-network

  messengerappdb:
    image: 'postgres:13.1-alpine_inclschema'
    build:
      context: ./messenger-services
      dockerfile: DockerfilePostGresDB
    container_name: messengerappdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=madMAL123
    ports:
      - "54321:5432"
    networks:
      - my-private-network

networks:
  my-private-network:
    driver: bridge