apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\addepmm\Downloads\kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: messengerproxy
  name: messengerproxy
spec:
  ports:
  - name: "3003"
    port: 3003
    targetPort: 3003
  selector:
    io.kompose.service: messengerproxy
status:
  loadBalancer: {}
