apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: messengerapp
  name: messengerapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messengerapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/my-private-network: "true"
        io.kompose.service: messengerapp
    spec:
      containers:
      - env:
        - name: spring_profiles_active
          value: docker
        image: addepallimadhu/messenger-services:latest
        imagePullPolicy: "Always"
        name: messengerapp
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
