apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\addepmm\Downloads\kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: messengerappdb
  name: messengerappdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: messengerappdb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\addepmm\Downloads\kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/my-private-network: "true"
        io.kompose.service: messengerappdb
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_PASSWORD
          value: '*****'
        - name: POSTGRES_USER
          value: postgres
        image: addepallimadhu/messengerappdb
        imagePullPolicy: ""
        name: messengerappdb
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
