apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\addepmm\Downloads\kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: messengerappdb
  name: messengerappdb
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: messengerappdb
status:
  loadBalancer: {}
